### ISSUE TITLE
External memory and frame sampling strategies

### ISSUE THREAD

**Issue by zpyi** [Malik1998/VSTAM#1]
Hello, it seems like this codebase do not contain the external memory module and frame sampling strategies, will you release them later？ And which type of gpus do you use? I can not reproduce it on 3090 due to out of memory. Thanks for your good work! ^_^

**Comment by Malik1998** [comment]
Hello, thank you for your feedback.
Yes, I will add them later, now I have the problems by adding video detection dataset, probably will just mock this data by using some random values.
Also there is no train model, will add this latter too.
I used  Tesla V100S

**Comment by Malik1998** [comment]
Hi, I've made draft pull request here https://github.com/Malik1998/VSTAM/pull/2
