### ISSUE TITLE
Predict video or stream

### ISSUE THREAD

**Issue by lbg030** [Malik1998/VSTAM#3]
How can I predict videos or streams and save them as result values?

**Comment by Malik1998** [comment]
Hello. It's still only draft implementation, now you can take a look to https://github.com/Malik1998/VSTAM/blob/main/example.py#L26- there I used model to infer on some random data. And also you may need https://github.com/Malik1998/VSTAM/blob/main/iterate_over_dataset.py#L19 to make use of cached data in your stream. Utils at the moment you must write by your self, but in the future I am planning to add them
