### ISSUE TITLE
ImageNet VID

### ISSUE THREAD

**Issue by prsbsvrn** [Malik1998/VSTAM#4]
Hi, can you tell me how you download ImageNet VID dataset? Their own site and [http://bvisionweb1.cs.unc.edu/ILSVRC2017/download-videos-1p39.php](url) for 2015, 2016 and 2017 doesn't work. Can you help me and suggest a way to solve this problem?

**Comment by Malik1998** [comment]
Hi, unfortunately I couldn't solve that problem too. So for educational purposes used random dataset, like in https://github.com/Malik1998/VSTAM/tree/main/mock_utils

**Comment by prsbsvrn** [comment]
> Hi, unfortunately I couldn't solve that problem too. So for educational purposes used random dataset, like in https://github.com/Malik1998/VSTAM/tree/main/mock_utils

Thanks for your reply.
