### ISSUE TITLE
VSTAM training

### ISSUE THREAD

**Issue by andy-sasa** [Malik1998/VSTAM#5]
Hi, can you supply some code about VSTAM?? I'm so confused how to use it to train in my custom dataset. 

Or give me some suggest?

**Comment by Malik1998** [comment]
Hello. It's still only draft implementation, now you can take a look to https://github.com/Malik1998/VSTAM/blob/main/example.py#L26- there I used model to infer on some random data. And also you may need https://github.com/Malik1998/VSTAM/blob/main/iterate_over_dataset.py#L19 to make use of cached data in your stream. Utils at the moment you must write by your self, but in the future I am planning to add them.
 Here (https://github.com/Malik1998/VSTAM/blob/main/data/dataset.py) you can see dataset with cached memory, that will choose best pictures to send to your model, according to scores you send through add_scores method.
And here (https://github.com/Malik1998/VSTAM/blob/main/transformer/video_sparse_transformer_decoder.py#L23) somehow scores getting method must be added

**Comment by andy-sasa** [comment]
Thank you for your reply.

Sorry, I want to ask another question.
In your code, you use view() in BaseBackbone.

![image](https://github.com/Malik1998/VSTAM/assets/116610423/110d0050-fe4a-4c1d-9d6f-7393004e3eba)

input_concated = input.view(input.size(0) * input.size(1), input.size(2), input.size(3), -1)

and then

feature_embeddings = feature_embeddings.view(input.size(0), input.size(1), -1, self.feature_embedder_out)

Will the time information between these frames not be lost?
ex. Seconds are(1, 2, 3, 4, 5), become (1, 3, 2, 4, 5)

**Comment by andy-sasa** [comment]
Thank you for your reply !

**Comment by andy-sasa** [comment]
> Hello. It's still only draft implementation, now you can take a look to https://github.com/Malik1998/VSTAM/blob/main/example.py#L26- there I used model to infer on some random data. And also you may need https://github.com/Malik1998/VSTAM/blob/main/iterate_over_dataset.py#L19 to make use of cached data in your stream. Utils at the moment you must write by your self, but in the future I am planning to add them. Here (https://github.com/Malik1998/VSTAM/blob/main/data/dataset.py) you can see dataset with cached memory, that will choose best pictures to send to your model, according to scores you send through add_scores method. And here (https://github.com/Malik1998/VSTAM/blob/main/transformer/video_sparse_transformer_decoder.py#L23) somehow scores getting method must be added

Thank you for your reply !
